-- MySQL Script generated by MySQL Workbench
-- 11/14/16 16:55:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema traepaka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema traepaka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `traepaka` DEFAULT CHARACTER SET utf8 ;
USE `traepaka` ;

-- -----------------------------------------------------
-- Table `traepaka`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traepaka`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `traepaka`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traepaka`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `description` VARCHAR(500) NULL,
  `image` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_product_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `traepaka`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `traepaka`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traepaka`.`chats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seller_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id_chat`),
  INDEX `fk_chat_seller_idx` (`seller_id` ASC),
  INDEX `fk_chat_buyer_idx` (`buyer_id` ASC),
  INDEX `fk_chat_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_chat_seller`
    FOREIGN KEY (`seller_id`)
    REFERENCES `traepaka`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chat_buyer`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `traepaka`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chat_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `traepaka`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `traepaka`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traepaka`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender` TINYINT(1) NULL,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_chat_idx` (`chat_id` ASC),
  CONSTRAINT `fk_message_chat`
    FOREIGN KEY (`chat_id`)
    REFERENCES `traepaka`.`chats` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
